<?php

namespace App\Http\Controllers;

use App\Exceptions\ActivepiecesException;
use App\Exceptions\InvalidMandalaImageException;
use App\Models\Book;
use App\Services\ActivepiecesClient;
use App\Services\MandalaStorageService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

/**
 * Receives the result of ONE mandala generated by the Activepieces flow.
 *
 * Auth: the secret issued with the request (only its sha256 is stored on the page),
 * sent as `X-Callback-Secret`, `Authorization: Bearer` or the `callback_secret` /
 * `secret` body field. The `request_token` must be the outstanding one; the token of
 * an already answered request gets a plain 200 (Activepieces may repeat a callback).
 *
 * Validation problems are always 4xx: the flow retries a callback only on 5xx.
 */
class ActivepiecesCallbackController extends Controller
{
    public function __construct(
        private readonly MandalaStorageService $storage,
        private readonly ActivepiecesClient $client,
    ) {}

    public function store(Request $request, string $uuid, ?int $position = null): JsonResponse
    {
        if (! $this->client->isEnabled()) {
            return response()->json(['error' => 'Activepieces integration is not configured.'], 503);
        }

        $book = Book::where('uuid', $uuid)->first();

        if ($book === null) {
            return response()->json(['error' => 'Book not found.'], 404);
        }

        $position ??= is_numeric($request->input('position')) ? (int) $request->input('position') : 0;

        if ($position < 1 || $position > $book->mandala_count) {
            return response()->json(['error' => "position must be between 1 and {$book->mandala_count}."], 422);
        }

        // One callback at a time per page: a repeated or racing delivery waits here and then
        // finds the token already answered.
        [$response, $advance] = DB::transaction(fn () => $this->process($request, $book, $position));

        if ($advance) {
            $response = $this->advanceQueue($book, $response);
        }

        return $response;
    }

    /** @return array{0: JsonResponse, 1: bool} response and whether the queue may go on */
    private function process(Request $request, Book $book, int $position): array
    {
        $mandala = $book->mandalas()->where('position', $position)->lockForUpdate()->firstOrFail();

        $hash = $mandala->callback_secret_hash;
        $secret = $this->providedSecret($request);

        if ($hash === null || $secret === '' || ! hash_equals($hash, ActivepiecesClient::hashSecret($secret))) {
            return [response()->json(['error' => 'Invalid secret.'], 401), false];
        }

        $token = $request->input('request_token');
        $token = is_string($token) ? $token : '';

        if ($token !== '' && $mandala->request_token !== null && hash_equals($mandala->request_token, $token)) {
            // outstanding request: process below
        } elseif ($token !== '' && $mandala->completed_token !== null && hash_equals($mandala->completed_token, $token)) {
            return [response()->json(['ok' => true, 'duplicate' => true, 'position' => $position]), false];
        } else {
            return [response()->json(['error' => 'request_token does not match the outstanding request.'], 409), false];
        }

        if ($request->filled('error')) {
            $code = $request->filled('error_code') ? Str::limit((string) $request->input('error_code'), 40, '') : null;

            Log::info('Activepieces callback received', ['book' => $book->uuid, 'position' => $position, 'result' => 'error', 'error_code' => $code]);

            $this->client->markFailed($mandala, (string) $request->input('error'), $code, answered: true);
            $this->client->stopQueue($book);

            return [response()->json(['ok' => false, 'status' => 'failed', 'position' => $position]), false];
        }

        try {
            $bytes = $this->imageBytes($request);

            Log::info('Activepieces callback received', [
                'book' => $book->uuid,
                'position' => $position,
                'result' => 'image',
                'bytes' => strlen($bytes),
                'sha1' => sha1($bytes),
            ]);

            $this->storage->storeBinary(
                $mandala,
                $bytes,
                basename((string) parse_url((string) $request->input('image_url'), PHP_URL_PATH)) ?: null,
                'activepieces',
                $request->filled('prompt') && is_string($request->input('prompt')) ? $request->input('prompt') : null,
                $token,
            );
        } catch (InvalidMandalaImageException $e) {
            $this->client->markFailed($mandala, $e->getMessage(), 'invalid_image');
            $this->client->stopQueue($book);

            return [response()->json(['error' => $e->getMessage()], 422), false];
        }

        return [response()->json(['ok' => true, 'position' => $position]), true];
    }

    /** Ask for the next page(s) once the transaction is committed; adds the result to the reply. */
    private function advanceQueue(Book $book, JsonResponse $response): JsonResponse
    {
        $book->refresh();
        $next = null;
        $queueError = null;

        if ($book->ai_queue_active) {
            try {
                $next = $this->client->requestNext($book)?->position;
            } catch (ActivepiecesException $e) {
                $queueError = $e->getMessage();
            }
        }

        return response()->json($response->getData(true) + [
            'book_status' => $book->fresh()->status->value,
            'next_requested' => $next,
            'queue_error' => $queueError,
        ]);
    }

    private function providedSecret(Request $request): string
    {
        return (string) ($request->header('X-Callback-Secret')
            ?: $request->bearerToken()
            ?: $request->input('callback_secret')
            ?: $request->input('secret')
            ?: '');
    }

    /** @throws InvalidMandalaImageException */
    private function imageBytes(Request $request): string
    {
        if ($request->filled('image_base64')) {
            $data = preg_replace(['#^data:image/[a-z+.-]+;base64,#i', '/\s+/'], '', (string) $request->input('image_base64'));
            $bytes = base64_decode($data, true);

            if ($bytes === false) {
                throw new InvalidMandalaImageException('image_base64 no es base64 válido.');
            }

            return $bytes;
        }

        $url = (string) $request->input('image_url');

        if (! preg_match('#^https?://#i', $url) || filter_var($url, FILTER_VALIDATE_URL) === false) {
            throw new InvalidMandalaImageException('Se requiere image_url (http/https) o image_base64.');
        }

        try {
            $response = Http::timeout(config('kawaii.activepieces.download_timeout_seconds'))->get($url);
        } catch (\Throwable $e) {
            throw new InvalidMandalaImageException('No se pudo descargar la imagen: '.$e->getMessage());
        }

        if (! $response->successful()) {
            throw new InvalidMandalaImageException('La descarga de la imagen devolvió HTTP '.$response->status().'.');
        }

        return $response->body();
    }
}
