<?php

namespace App\Http\Controllers;

use App\Exceptions\ActivepiecesException;
use App\Exceptions\InvalidMandalaImageException;
use App\Models\Book;
use App\Services\ActivepiecesClient;
use App\Services\MandalaStorageService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;

/**
 * Receives the result of ONE mandala generated by the Activepieces flow.
 *
 * Auth: shared secret via `X-Callback-Secret` header, `Authorization: Bearer`,
 * or the `callback_secret` / `secret` body field (Activepieces echoes the value
 * it received in the request payload).
 */
class ActivepiecesCallbackController extends Controller
{
    public function __construct(
        private readonly MandalaStorageService $storage,
        private readonly ActivepiecesClient $client,
    ) {}

    public function store(Request $request, string $uuid, ?int $position = null): JsonResponse
    {
        $expected = (string) config('kawaii.activepieces.shared_secret');

        if (! $this->client->isEnabled() || strlen($expected) < ActivepiecesClient::MIN_SECRET_LENGTH) {
            return response()->json(['error' => 'Activepieces integration is not configured.'], 503);
        }

        if (! hash_equals($expected, $this->providedSecret($request))) {
            return response()->json(['error' => 'Invalid secret.'], 401);
        }

        $book = Book::where('uuid', $uuid)->first();

        if ($book === null) {
            return response()->json(['error' => 'Book not found.'], 404);
        }

        $position ??= is_numeric($request->input('position')) ? (int) $request->input('position') : 0;

        if ($position < 1 || $position > $book->mandala_count) {
            return response()->json(['error' => "position must be between 1 and {$book->mandala_count}."], 422);
        }

        $mandala = $book->mandalas()->where('position', $position)->firstOrFail();

        // A slot with an outstanding request only accepts the token issued for it.
        if ($mandala->request_token !== null
            && ! hash_equals($mandala->request_token, (string) $request->input('request_token'))) {
            return response()->json(['error' => 'request_token does not match the outstanding request.'], 409);
        }

        $wasRequested = $mandala->request_token !== null;

        if ($request->filled('error')) {
            $this->client->markFailed($mandala, (string) $request->input('error'));
            $this->client->stopQueue($book);

            return response()->json(['ok' => false, 'status' => 'failed', 'position' => $position]);
        }

        try {
            $bytes = $this->imageBytes($request);
            $this->storage->storeBinary(
                $mandala,
                $bytes,
                basename((string) parse_url((string) $request->input('image_url'), PHP_URL_PATH)) ?: null,
                'activepieces',
                $request->filled('prompt') ? (string) $request->input('prompt') : null,
            );
        } catch (InvalidMandalaImageException $e) {
            $this->client->markFailed($mandala, $e->getMessage());
            $this->client->stopQueue($book);

            return response()->json(['error' => $e->getMessage()], 422);
        }

        $book->refresh();
        $next = null;
        $queueError = null;

        if ($wasRequested && $book->ai_queue_active) {
            try {
                $next = $this->client->requestNext($book)?->position;
            } catch (ActivepiecesException $e) {
                $queueError = $e->getMessage();
            }
        }

        return response()->json([
            'ok' => true,
            'position' => $position,
            'book_status' => $book->fresh()->status->value,
            'next_requested' => $next,
            'queue_error' => $queueError,
        ]);
    }

    private function providedSecret(Request $request): string
    {
        return (string) ($request->header('X-Callback-Secret')
            ?: $request->bearerToken()
            ?: $request->input('callback_secret')
            ?: $request->input('secret')
            ?: '');
    }

    /** @throws InvalidMandalaImageException */
    private function imageBytes(Request $request): string
    {
        if ($request->filled('image_base64')) {
            $data = preg_replace('#^data:image/[a-z]+;base64,#i', '', (string) $request->input('image_base64'));
            $bytes = base64_decode($data, true);

            if ($bytes === false) {
                throw new InvalidMandalaImageException('image_base64 no es base64 válido.');
            }

            return $bytes;
        }

        $url = (string) $request->input('image_url');

        if (! preg_match('#^https?://#i', $url) || filter_var($url, FILTER_VALIDATE_URL) === false) {
            throw new InvalidMandalaImageException('Se requiere image_url (http/https) o image_base64.');
        }

        try {
            $response = Http::timeout(config('kawaii.activepieces.download_timeout_seconds'))->get($url);
        } catch (\Throwable $e) {
            throw new InvalidMandalaImageException('No se pudo descargar la imagen: '.$e->getMessage());
        }

        if (! $response->successful()) {
            throw new InvalidMandalaImageException('La descarga de la imagen devolvió HTTP '.$response->status().'.');
        }

        return $response->body();
    }
}
